[project]
name = "noetheragent"
version = "0.0.1"
requires-python = ">=3.11"
description = "Closed-loop discovery with OED + formal check"
authors = [{name="You"}]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
